language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angular-wakanda' ]; then cd .. && eval "mv $currentfolder generator-angular-wakanda" && cd generator-angular-wakanda; fi

